#!/usr/bin/env python3

import datetime
import locale
import sqlite3
from argparse import ArgumentParser, FileType
from functools import wraps

import telegram.request
from telegram.ext import *
import telegram.ext.filters

from bot_types import *
from storage import Storage

log = logging.getLogger(__name__)
logging.getLogger("asyncio").setLevel(logging.WARNING)
logging.captureWarnings(True)

DMITRY_BOGDANOV = 160453507  # type: int

global storage


class STATE:
    WAIT_FOR_PLACE = 0
    WAIT_FOR_DATE = 1
    WAIT_FOR_TIME = 2


def actualize_users(handler):
    @wraps(handler)
    def wrapped(update: Update, context: CallbackContext):
        storage.upsert_user(update.effective_user)
        return handler(update, context)

    return wrapped


def admins_only(handler):
    @wraps(handler)
    def wrapped(update: Update, context: CallbackContext):
        user = update.effective_user  # type: User
        if user.id != DMITRY_BOGDANOV:
            chat = update.effective_chat  # type: Chat
            context.bot.send_message(chat_id=chat.id, text='You are not my master')
            return ConversationHandler.END
        else:
            return handler(update, context)

    return wrapped


@actualize_users
@admins_only
async def handle_start(update: Update, context: CallbackContext):
    log.info(f'user {update.effective_user} started conversation')

    storage.start_sessions(update.effective_user)

    places = storage.select_places()
    keyboard = [[p] for p in places.values()]
    reply_markup = ReplyKeyboardMarkup(keyboard, one_time_keyboard=True, resize_keyboard=True)

    await update.message.reply_markdown_v2('Что? - и так понятно. Где?', reply_markup=reply_markup)

    return STATE.WAIT_FOR_PLACE


@actualize_users
@admins_only
async def handle_place(update: Update, context: CallbackContext):
    log.info(f'user {update.effective_user} sent place')
    msg = update.message  # type: Message
    place = msg.text_markdown_v2
    storage.set_place_in_session(update.effective_user, place)

    today = datetime.date.today()
    keyboard = []  # type: List[List[str]]
    columns = 2
    rows = 4
    for i in range(rows):
        keyboard.append([])
        for j in range(columns):
            day = today + datetime.timedelta(days=columns * i + j)
            keyboard[i].append(day.strftime('%d.%m (%A)'))
    markup = ReplyKeyboardMarkup(keyboard, one_time_keyboard=True, resize_keyboard=True)

    await update.message.reply_markdown_v2('Когда?', reply_markup=markup)

    return STATE.WAIT_FOR_DATE


@actualize_users
@admins_only
async def handle_date(update: Update, context: CallbackContext):
    log.info(f'user {update.effective_user} sent date')

    today = datetime.date.today()

    date_str = update.message.text  # type: str
    date_str = date_str.split(' ')[0]
    date = datetime.datetime.strptime(date_str, '%d.%m').date()
    date = date.replace(year=today.year)
    if date < today:
        date = date.replace(today.year + 1)

    storage.set_date_in_session(update.effective_user, date)

    markup = ReplyKeyboardMarkup(keyboard=[["11:00", "11:11", "19:00", "19:05"]], one_time_keyboard=True,
                                 resize_keyboard=True)

    await update.message.reply_markdown_v2('А точнее?', reply_markup=markup)

    return STATE.WAIT_FOR_TIME


@actualize_users
@admins_only
async def list_places(update: Update, context: CallbackContext):
    log.info(f'asked for list places')
    places = storage.select_places()
    text = '<No places are saved>'  if len(places) == 0 else '\n'.join([f'{p[0]}) {p[1]}' for p in places.items()])
    await update.message.reply_markdown_v2(text)
    return None


@actualize_users
@admins_only
async def remove_place(update: Update, context: CallbackContext):
    message = update.message  # type: Message
    command = message.entities[0]  # type: MessageEntity
    place_id = int(message.text[command.offset + command.length + 1:])
    storage.remove_place(place_id)
    return None


def poll_text(header: str) -> str:
    return f'{header}\n\nОбкашляем вопросики?'

def poll_header(place: str, date: datetime.date, time: datetime.time) -> str:
    return f'{date.strftime("%d %B %Y, %A")}. {time.strftime("%H:%M")}. {place}'


@actualize_users
@admins_only
async def create_poll(update: Update, context: CallbackContext):
    msg = update.message  # type: Message
    command_entity = msg.entities[0]  # type: MessageEntity
    text = msg.text_markdown_v2[command_entity.offset + command_entity.length + 1:]
    poll_id = storage.insert_poll(Poll(poll_text(text)))
    await send_saved_poll(context.bot, update.message.chat.id, poll_id)
    return ConversationHandler.END


@actualize_users
@admins_only
async def handle_time(update: Update, context: CallbackContext):
    log.info(f'user {update.effective_user} sent time')

    time_str = update.message.text  # type: str
    time = datetime.datetime.strptime(time_str, '%H:%M').time()

    storage.set_time_in_session(update.effective_user, time)

    (place, date, time) = storage.get_session(update.effective_user)

    text = poll_text(poll_header(place, date, time))
    poll_id = storage.insert_poll(Poll(text))

    await send_saved_poll(context.bot, update.message.chat.id, poll_id)

    return ConversationHandler.END


async def send_saved_poll(bot: Bot, chat_id: int, poll_id: PollId):
    poll = storage.select_poll(poll_id=poll_id)
    sent_message = await bot.send_message(chat_id=chat_id,
                                          text=poll.build_text(),
                                          parse_mode=constants.ParseMode.MARKDOWN_V2,
                                          reply_markup=poll.build_markup(),
                                          )
    await bot.send_message(chat_id=chat_id, text='Готово. Ещё? press /newpoll', reply_markup=ReplyKeyboardRemove())
    sent_message_id = MessageId(chat_id=sent_message.chat_id, message_id=sent_message.message_id)
    storage.insert_message(poll_id, sent_message_id)


async def update_poll_message(bot: Bot, poll: PollExt, msg: MessageId):
    try:
        log.debug(f'Updating message {msg} for poll {poll}...')
        await bot.edit_message_text(chat_id=msg.chat_id,
                                    message_id=msg.message_id,
                                    inline_message_id=msg.inline_message_id,
                                    text=poll.build_text(),
                                    parse_mode=constants.ParseMode.MARKDOWN_V2,
                                    reply_markup=poll.build_markup(),
                                    )
        log.debug(f'Up-to-date')
    except Exception as e:
        log.error(f'Cannot edit: {e}')


async def update_poll_messages(bot: Bot, poll_id: PollId):
    messages = storage.select_messages(poll_id)
    poll = storage.select_poll(poll_id)
    log.debug(f'About to update {len(messages)} messages')
    for msg in messages:
        await update_poll_message(bot, poll, msg)


@actualize_users
async def handle_vote(update: Update, context: CallbackContext):
    log.debug("handling vote")
    query = update.callback_query  # type: CallbackQuery

    def parse_vote_data(data: str):
        [poll_id_str, option_id] = data.split(':')
        return int(poll_id_str), OPTION.from_string(option_id)

    poll_id, option = parse_vote_data(query.data)

    log.info(f'user {update.effective_user} vote for {option} in poll {poll_id}')

    storage.vote(poll_id, update.effective_user, option)

    await update_poll_messages(context.bot, poll_id)
    await query.answer()
    log.debug("vote handled")
    return None


@actualize_users
async def handle_inline_query(update: Update, context: CallbackContext):
    query = update.inline_query  # type: InlineQuery
    poll_id = int(query.query)
    poll_ext = storage.select_poll(poll_id)
    bot = context.bot  # type: Bot
    await bot.answer_inline_query(cache_time=0,
                                  inline_query_id=query.id,
                                  results=[InlineQueryResultArticle(
                                      id=poll_id,
                                      title=poll_ext.text,
                                      input_message_content=InputTextMessageContent(
                                          message_text=poll_ext.build_text(),
                                          parse_mode=constants.ParseMode.MARKDOWN_V2,
                                      ),
                                      reply_markup=poll_ext.build_markup()
                                  )],
                                  )
    return None


@actualize_users
async def handle_chosen_inline_query(update: Update, context: CallbackContext):
    query = update.chosen_inline_result  # type: ChosenInlineResult
    poll_id = int(query.query)
    message_id = MessageId(inline_message_id=query.inline_message_id)
    storage.insert_message(poll_id, message_id)
    return None


@actualize_users
@admins_only
async def handle_add_place(update: Update, context: CallbackContext):
    log.info(f'Adding place: {update.message}')
    msg = update.message  # type: Message
    command = msg.entities[0]  # type: MessageEntity
    place = msg.text[(command.length + command.offset + 1):]
    storage.insert_place(place)

    return None


def main():
    locale.setlocale(locale.LC_TIME, "ru_RU.UTF-8")

    parser = ArgumentParser()
    parser.add_argument('--proxy', type=str)
    parser.add_argument('--db', type=str, required=True)
    parser.add_argument('-v', '--verbose', action='store_true')
    token_args = parser.add_mutually_exclusive_group(required=True)
    token_args.add_argument('--token_file', type=FileType('r'))
    token_args.add_argument('--token', type=str)

    args = parser.parse_args()

    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(level=log_level,
                        format='[%(asctime)s %(filename)s:%(lineno)d:%(funcName)s %(name)s] %(levelname)s: %(message)s')

    token = args.token_file.readline().rstrip() if args.token_file is not None else args.token

    connection = sqlite3.connect(args.db,
                                 detect_types=sqlite3.PARSE_DECLTYPES | sqlite3.PARSE_COLNAMES,
                                 check_same_thread=False)
    global storage
    storage = Storage(connection)

    req = telegram.request.HTTPXRequest(proxy_url=args.proxy, connection_pool_size=8)
    app = (Application.builder()
           .request(req)
           .token(token)
           .build())

    app.add_handler(ConversationHandler(
        entry_points=[
            CommandHandler(['start', 'reset', 'newpoll', 'new_poll'], handle_start),
            CommandHandler(['add_place'], handle_add_place),
            CommandHandler(['list_places'], list_places),
            CommandHandler(['remove_place'], remove_place),
            CommandHandler(['create_poll'], create_poll)
        ],
        states={
            STATE.WAIT_FOR_PLACE: [MessageHandler(telegram.ext.filters.TEXT, handle_place)],
            STATE.WAIT_FOR_DATE: [MessageHandler(telegram.ext.filters.TEXT, handle_date)],
            STATE.WAIT_FOR_TIME: [MessageHandler(telegram.ext.filters.TEXT, handle_time)]
        },
        fallbacks=[]
    ))
    app.add_handler(CallbackQueryHandler(
        callback=handle_vote
    ))
    app.add_handler(InlineQueryHandler(callback=handle_inline_query))
    app.add_handler(ChosenInlineResultHandler(callback=handle_chosen_inline_query))

    app.run_polling(allowed_updates=Update.ALL_TYPES, timeout=60)


if __name__ == '__main__':
    main()
